[package]
name = "logger"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["dylib", "rlib"]

[features]
log = ["dep:log"]

[dependencies]
colored = "2.1.0"
log = { version = "0.4.22", optional = true }
